### ISSUE TITLE
No menu item to run analyzer

### ISSUE THREAD

**Issue by clarktrip1** [mariazevedo88/o3smeasures-tool#24]
I've installed Eclipse 2020-09 and used the Marketplace client to install O3SMeasures.  I opened a workspace that has some projects from various Git repos.  I opened the 5 views in _Window > Show Views > Other... > o3smeasures_.  When I right click a Java based project, there is no "_O3SMeasures -> Analyze Java project_" on the context menu.  How do I analyze my code?  There's nothing that shows up in the workspace's .log file that relevant; only some key binding stuff.

!SESSION 2020-12-01 11:38:49.326 -----------------------------------------------
eclipse.buildId=4.17.0.I20200902-1800
java.version=11.0.8
java.vendor=Red Hat, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

**Comment by mariazevedo88** [comment]
@clarktrip1 Hi Clark! 

Sorry for taking so much time to send feedback to you. I've been analyzing your report carefully, in my free time, since December. I tried to reproduce the error running the plugin in different Java versions (8,11, and 14, for example) and different Java projects (simple Java projects, Maven-based projects, Spring projects). In all of them, the plugin worked smoothly (please see the prints of one of these tests below):

![o3smeasures-2](https://user-images.githubusercontent.com/1054867/105779742-c2305500-5f4d-11eb-933c-4545af343cc6.png)
 
![o3smeasures-1](https://user-images.githubusercontent.com/1054867/105779758-c9576300-5f4d-11eb-9cfe-9a79b97b6646.png)

The only thing that caught my attention is your ```java.vendor```. I am using ```java.vendor=Oracle Corporation``` (Oracle's JDK), and it is working for me. Could you please try to run the tool in a similar configuration? 

`
eclipse.buildId=4.17.0.I20200902-1800
java.version=14.0.2
java.vendor=Oracle Corporation
`
Do not forget to set up your Eclipse in the right views: Package Explorer and Java or Java EE perspectives.

Please, let me know if solved. If you can run it, I believe the problem is in the JDK vendor.
